// Auto-generated by tools/design-v5-phase0/extractors/interfaces_extractor.py
// Source: design-v4 run prose. Stubs only — bodies intentionally absent.

#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MeshOS.DesignV5.Phase0.Contracts;

public sealed record Result<T>(bool Ok, T? Value, string? Error);


